apiVersion: v1
kind: Secret
metadata:
  name: streamingapp-secrets
  namespace: streamingapp
type: Opaque
stringData:
  JWT_SECRET: changeme
  MONGO_URI: mongodb://change-me/streamingapp
  AWS_ACCESS_KEY_ID: replace-me
  AWS_SECRET_ACCESS_KEY: replace-me
  AWS_S3_BUCKET: replace-me